import deepmerge from 'deepmerge';
import type { BuildOptions } from 'esbuild';
import type { TransformOptions } from '@babel/core';
import type { Options as SWCOptions } from '@swc/core';
import { SOURCE_EXTENSIONS, ASSET_EXTENSIONS, BANNER_VARS } from './shares';
import type { EsbuildPresetOptions, SWCPresetOptions } from './types';

function getESbuildOptions(
  options: EsbuildPresetOptions,
  customOptions?: Partial<BuildOptions>,
): BuildOptions {
  const { platform, dev } = options;

  const platforms = [platform, 'native', 'react-native'];
  const extensions = SOURCE_EXTENSIONS.concat(ASSET_EXTENSIONS);

  const getReactNativePolyfills = (): (() => unknown[]) => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    return require(require.resolve(
      'react-native/rn-get-polyfills',
    )) as () => unknown[];
  };

  return deepmerge(
    {
      mainFields: ['react-native', 'browser', 'module', 'main'],
      minify: !dev,
      resolveExtensions: platforms
        .map((p) => extensions.map((e) => `.${p}${e}`))
        .concat(extensions)
        .flat(),
      define: {
        __DEV__: JSON.stringify(dev),
        global: 'window',
        'process.env.NODE_ENV': JSON.stringify(
          dev ? 'development' : 'production',
        ),
      },
      loader: {
        '.js': 'jsx',
        ...Object.fromEntries(ASSET_EXTENSIONS.map((ext) => [ext, 'file'])),
      },
      legalComments: 'none',
      banner: {
        js: `var ${BANNER_VARS.join(',')};`,
      },
      inject: [
        ...getReactNativePolyfills()(),
        'react-native/Libraries/Core/InitializeCore',
      ],
      target: 'es6',
      supported: {
        // to avoid block scope bug on hermes engine.
        // in `__copyProps`, generated by esbuild
        'for-of': false,
      },
      format: 'iife',
      bundle: true,
      sourcemap: true,
    },
    customOptions ?? {},
  );
}

function getBabelOptions(
  customOptions?: Partial<TransformOptions>,
): TransformOptions {
  const baseOptions = {
    minified: false,
    compact: false,
    sourceMaps: false,
  };

  return customOptions ? deepmerge(baseOptions, customOptions) : baseOptions;
}

function getSWCOptions(
  options: SWCPresetOptions,
  customOptions?: Partial<SWCOptions>,
): SWCOptions {
  const isTS = /\.tsx?$/.test(options.filename);

  const baseOptions: SWCOptions = {
    isModule: true,
    sourceMaps: false,
    jsc: {
      parser: {
        syntax: isTS ? 'typescript' : 'ecmascript',
        [isTS ? 'tsx' : 'jsx']: true,
        dynamicImport: true,
        functionBind: false,
        exportDefaultFrom: true,
        decorators: false,
        decoratorsBeforeExport: false,
        importAssertions: false,
      },
      transform: undefined,
      target: 'es5',
      loose: true,
      externalHelpers: true,
      keepClassNames: true,
    },
  };

  return customOptions ? deepmerge(baseOptions, customOptions) : baseOptions;
}

export { getESbuildOptions, getBabelOptions, getSWCOptions };
export * from './shares';
export type * from './types';
