import path from 'node:path';
import deepmerge from 'deepmerge';
import type { BuildOptions } from 'esbuild';
import {
  DEFAULT_ENTRY_POINT,
  DEFAULT_OUTFILE,
  SOURCE_EXTENSIONS,
  ASSET_EXTENSIONS,
} from '../shares';
import type { BundleConfig } from '../types';
import {
  getInjectVariables,
  getGlobalVariables,
  getReactNativePolyfills,
  REACT_NATIVE_INITIALIZE_CORE_MODULE,
} from './reactNativeInternal';

export function getEsbuildOptions(
  bundleConfig: BundleConfig,
  customEsbuildOptions?: Partial<BuildOptions>,
): BuildOptions {
  const {
    entry = DEFAULT_ENTRY_POINT,
    outfile = DEFAULT_OUTFILE,
    platform,
    minify,
  } = bundleConfig;
  const dev = Boolean(bundleConfig.dev);

  const platforms = [platform, 'native', 'react-native'];
  const extensions = SOURCE_EXTENSIONS.concat(ASSET_EXTENSIONS);

  const baseOptions: BuildOptions = {
    /**
     * mainFields
     * @see {@link https://github.com/facebook/metro/blob/0.72.x/docs/Configuration.md#resolvermainfields}
     */
    mainFields: ['react-native', 'browser', 'main', 'module'],
    entryPoints: [entry],
    outfile,
    sourceRoot: path.dirname(entry),
    resolveExtensions: platforms
      .map((platform) => extensions.map((ext) => `.${platform}${ext}`))
      .concat(extensions)
      .flat(),
    define: getGlobalVariables(Boolean(dev)),
    loader: Object.fromEntries(ASSET_EXTENSIONS.map((ext) => [ext, 'file'])),
    legalComments: 'none',
    banner: {
      js: `var ${getInjectVariables(dev).join(',')};`,
    },
    inject: [REACT_NATIVE_INITIALIZE_CORE_MODULE, ...getReactNativePolyfills()],
    target: 'es6',
    supported: {
      /**
       * to avoid block scope bug on hermes engine.
       * in `__copyProps`, generated by esbuild
       *
       * @see {@link https://github.com/evanw/esbuild/blob/v0.18.17/internal/runtime/runtime.go#L192}
       */
      'for-of': false,
    },
    format: 'iife',
    bundle: true,
    sourcemap: true,
    minify,
    logLevel: 'silent',
  };

  return deepmerge(baseOptions, customEsbuildOptions ?? {});
}
