import path from 'node:path';
import deepmerge from 'deepmerge';
import type { BuildOptions } from 'esbuild';
import { SOURCE_EXTENSIONS, ASSET_EXTENSIONS } from '../shares';
import type { BundleOptions } from '../types';

export const getEsbuildOptions = (
  bundleOptions: BundleOptions,
  customEsbuildOptions?: Partial<BuildOptions>,
): BuildOptions => {
  const { entry, outfile, platform, minify, metafile } = bundleOptions;

  const platforms = [platform, 'native', 'react-native'];
  const extensions = SOURCE_EXTENSIONS.concat(ASSET_EXTENSIONS);

  const baseOptions: BuildOptions = {
    entryPoints: [entry],
    outfile,
    sourceRoot: path.dirname(entry),
    resolveExtensions: platforms
      .map((platform) => extensions.map((ext) => `.${platform}${ext}`))
      .concat(extensions)
      .flat(),
    loader: Object.fromEntries(ASSET_EXTENSIONS.map((ext) => [ext, 'file'])),
    legalComments: 'none',
    target: 'es6',
    supported: {
      /**
       * to avoid block scope bug on hermes engine.
       * in `__copyProps`, generated by esbuild
       *
       * @see {@link https://github.com/evanw/esbuild/blob/v0.18.17/internal/runtime/runtime.go#L192}
       */
      'for-of': false,
    },
    format: 'esm',
    bundle: true,
    sourcemap: true,
    minify,
    metafile,
    logLevel: 'silent',
  };

  return deepmerge(baseOptions, customEsbuildOptions ?? {});
};
