name: deploy-docs

on:
  push:
    branches:
      - master

jobs:
  hook:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-docs
        if: contains(github.event.head_commit.message, 'docs:')
        run: |
          curl -X POST -d {} ${{ vars.DOCS_DEPLOY_HOOK }}
